version: "3"
services:
  db:
    image: "postgres:15.4"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=amsssid
      - POSTGRES_DB=RMS-TS